name = "your-project-name"
compatibility_date = "2024-12-19"

[[d1_databases]]
binding = "DB"
database_name = "your-database-name"
database_id = "your-database-id"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "your-bucket-name"
preview_bucket_name = "your-preview-bucket-name"